Создание схемы БД личного проекта
htmlacademy-php/784693-yeticave-12 pull request #10
Opened 2021-05-31 15:17 UTC by Gambi99

2021-05-31 19:53 UTC, andrewverner requested changes

2021-05-31 19:53 UTC, andrewverner commented on schema.sql
> +                                                `lot_bidcol` VARCHAR(45) NULL,
`lot_bidcol` что это за колонка?

2021-05-31 19:53 UTC, andrewverner commented on schema.sql
> +                                             `contacts` TEXT NOT NULL,
Проверь ТЗ. `name` и `contacts` обязательны у пользователя? С ограничениями `NOT NULL` на этих полях эти данные придётся указывать при регистрации, иначе попытка создать пользователя с недостающими данными вызовет ошибку. Имя и контакты есть на форме регистрации?

2021-09-07 14:37 UTC, hennessyAnn reviewed
Привет! Написала замечания по реквесту, для более быстрой связи прошу писать в телеграм)

2021-09-07 14:37 UTC, hennessyAnn commented on schema.sql
> +CREATE TABLE IF NOT EXISTS `yeti`.`user` (
стоит добавить колонку с датой регистрации типа TIMESTAMP DEFAULT CURRENT_TIMESTAMP

2021-09-07 14:37 UTC, hennessyAnn commented on schema.sql
> +                                             `password` CHAR(32) NOT NULL,
поле мало, лучше использовать VARCHAR(255)

2021-09-07 14:37 UTC, hennessyAnn commented on schema.sql
> +                                             `email` VARCHAR(45) NOT NULL,
нужно увеличить размерность поля

2021-09-07 14:37 UTC, hennessyAnn commented on schema.sql
> +                                             `name` VARCHAR(45) NOT NULL,
нужно увеличить размерность поля

2021-09-07 14:37 UTC, hennessyAnn commented on schema.sql
> +                                             `contacts` TEXT NOT NULL,
действительно, лучше не делать поле contacts обязательным для заполнения

2021-09-07 14:37 UTC, hennessyAnn commented on schema.sql
> +CREATE TABLE IF NOT EXISTS `yeti`.`lot` (
добавить поле create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP

2021-09-07 14:37 UTC, hennessyAnn commented on schema.sql
> +CREATE TABLE IF NOT EXISTS `yeti`.`lot` (
добавить поле для хранения ссылки на файл link TEXT NOT NULL

2021-09-07 14:37 UTC, hennessyAnn commented on schema.sql
> +CREATE TABLE IF NOT EXISTS `yeti`.`lot` (
добавить поле id победителя ставки

2021-09-07 14:37 UTC, hennessyAnn commented on schema.sql
> +CREATE TABLE IF NOT EXISTS `yeti`.`lot_image` (
не обязательно создавать отдельную таблицу, можно оставить только ссылку на файл в таблице lot

2021-09-07 14:37 UTC, hennessyAnn commented on schema.sql
> +                                                `lot_bidcol` VARCHAR(45) NULL,
присоединяюсь к вопросу, что за колонка lot_bidcol?

2021-09-07 14:37 UTC, hennessyAnn commented on schema.sql
> +                                                `price` INT NOT NULL,
можно использовать тип DECIMAL

2021-09-10 13:50 UTC, Gambi99 commented on schema.sql
> +                                             `contacts` TEXT NOT NULL,
Денчик напомни пожалуйста где я могу проерить ТЗ? он в самом коде где та прописан или вhtmlacademy?
просто я не нашёл ТЗ подробное.. забыл где находиться.

2021-09-12 10:58 UTC, Gambi99 commented on schema.sql
> +                                                `lot_bidcol` VARCHAR(45) NULL,
Денис, мы вместе создали всё по шагам)) я тоже присоединяюсь к вопросу, давайте вместе разберёмся))

2021-09-15 21:44 UTC, merged